
name: Java CI

on:
  push:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK 8
      uses: actions/setup-java@v3
      with:
        java-version: '8'
        distribution: 'temurin'


    - name: Build with Maven
      run: mvn package --file pom.xml
    
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        
    - name: Analisis SonarCloud
      run: |
        mvn clean verify org.sonarsource.scanner.maven:sonar-maven-plugin:3.11.0.3922:sonar \
        -Dsonar.token=${{ secrets.SONAR_TOKEN }} \
        -Dsonar.host.url=https://sonarcloud.io \
        -Dsonar.organization=clagosu \
        -Dsonar.projectKey=clagosu_microservicio-java

    - name: Docker build
      run: |
        docker build -t clagosu/test:latest .
        docker images
