name: CI

on:
  push:
  workflow_dispatch:
  
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Cache Gradle packages
        uses: actions/cache@v3
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: ${{ runner.os }}-gradle
          
      - name: Build with Gradle
        run: |
          chmod +x gradlew
          ./gradlew build
          ls -lah $GITHUB_WORKSPACE/build/libs/
          
      - name: Archive artifact java app
        if: success()
        uses: actions/upload-artifact@v3
        with:
          name: java-app
          path: build/libs/testing-web-0.0.1-SNAPSHOT.jar
  
  dockerbuild:
    name: Docker build
    runs-on: ubuntu-latest
    needs: build
    if: success()
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Docker login
        uses: docker/login-action@v2.2.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Download artifact java app
        uses: actions/download-artifact@v3
        with:
          name: java-app
          path: .
          
      - name: Docker build
        run: |
          chmod 755 testing-web-0.0.1-SNAPSHOT.jar
          ls -lah
          docker build --tag lobozoldick/microservicio-java:latest .
          docker images

      - name: Docker push
        run: |
          docker push lobozoldick/microservicio-java

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@master
        with:
          project_id: ${{ secrets.GCLOUD_PROJECT_ID }}
          service_account_key: ${{ secrets.GCLOUD_SA_KEY }}
          export_default_credentials: true

      - name: Deploy to Google Cloud Run
        run: |
          gcloud run deploy microservicio-java \
            --image gcr.io/devops-v6-microservicio-java/lobozoldick/microservicio-java:latest \
            --platform managed \
            --region us-central1
        env:
          GCLOUD_PROJECT_ID: ${{ secrets.GCLOUD_PROJECT_ID }}
  
