name: CI

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Nueva rama con nombre
      uses: actions/checkout@v2

    - name: Crea una nueva rama y se ubica en ella
      run: |
        git checkout -b feature-ms-diegoLucero-mensaje
